### ISSUE TITLE
For @Neves-P: contribute to Snow White summary

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cicone#17]
* Difficulty: 2/10

Contribute to the Snow White plot summary at the bottom of README.md (
for inspiration, see [the Wikipedia page](https://en.wikipedia.org/wiki/Snow_White#Story)).
Do this from your branch on your local computer.
Check if the layout remains pretty from the GitHub website.
If the layout remains pretty, merge your work to the `develop` branch

**Comment by Neves-P** [comment]
Done!
