### ISSUE TITLE
For @Neves-P: contribute to Snow White summary on master

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cicone#53]
* Difficulty: 2/10

Contribute to the Snow White plot summary at the bottom of README.md (
for inspiration, see [the Wikipedia page](https://en.wikipedia.org/wiki/Snow_White#Story)).
Do this on the `master` branch on your local computer.
No need to check the layout: there will be merge conflicts :-).

**Comment by Neves-P** [comment]
Did the thing!
